branch-defaults:
  master:
    environment: stage
environment-defaults:
  stage:
    branch: null
    repository: null
global:
  application_name: series
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-east-2::platform/Puma with Ruby 2.3
    running on 64bit Amazon Linux/2.4.4
  default_region: us-east-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: series
  sc: git
  workspace_type: Application
